### ISSUE TITLE
2 $.ajaxじゃなくてfetch使いたい

### ISSUE THREAD

**Issue by sgrynd** [UCDM/practice-2#22]
https://developer.mozilla.org/ja/docs/Web/API/Fetch_API/Using_Fetch
https://qiita.com/tomoyukilabs/items/9b464c53450acc0b9574

参考までに。
https://github.com/sotoasobi/sotoasobiAppReactnative/blob/dc6d575c651a1aa8e7175342dfb59108572ada6e/src/components/Screens/MessageRoom.js#L82

**Comment by UCDM** [comment]
#32 reduxでjsonを取得する仕組みを作った (PR #30 )

**Comment by UCDM** [comment]
axionのgetを使って取得しする仕組みを作った
